=== tria-db/rxs2tria/inst/extdata/json_schema/base_schema/20251007_tria_metadata_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "TODO:addurltoTRIAschema",
    "title": "TRIA metadata schema",
    "description": "Schema for ...",
    "$comment": "use htType for ht renderers (add to all? or infer via type?), use otherChecks for extra/complex validations (implement)",
    "type": "object",
    "properties":
    {
        "ds_data": { "$ref": "20251007_tria_ds_data_schema.json" },
        "author_data": { "$ref": "20251007_tria_author_data_schema.json" },
        "funding_data": { "$ref": "20251007_tria_funding_data_schema.json" },
        "relresource_data": { "$ref": "20251007_tria_relresource_data_schema.json" },
        "site_data": { "$ref": "20251007_tria_site_data_schema.json" },
        "tree_data": { "$ref": "20251007_tria_tree_data_schema.json" },
        "woodpiece_data": { "$ref": "20251007_tria_woodpiece_data_schema.json" },
        "slide_data": { "$ref": "20251007_tria_slide_data_schema.json" },
        "roxas_data": { "$ref": "20251007_tria_roxas_data_schema.json" }
    },
    "required":
    [
        "ds_data",
        "author_data",
        "funding_data",
        "site_data",
        "tree_data",
        "woodpiece_data",
        "slide_data",
        "roxas_data"
    ],
    "additionalProperties": true
}

=== tria-db/rxs2tria/inst/extdata/20251015_TRIA_POGSTO2024_collected_metadata.json
{
    "$schema": "/Users/maranaegelin/Documents/code/Rcode/rxs2xcell/inst/extdata/json_schema/base_schema/20251007_tria_metadata_schema.json",
    "ds_data":
    [
        {
            "ds_name": "POGSTO1955",
            "description":"This dataset contains 3 trees of Pinus sylvestris collected in Pogorelsky and Stolby (Russia), covering the period from 1955 to 2018. The selected trees used in this collection are a selected subset from the original collected ad archived wood.",
            "ds_access": "public",
            "ds_license": "CC BY 4.0",
            "embargoed_until": "",
            "acknowledgements": ""
        }

    ],
    "author_data":
    [
        {
            "author_nr": 1,
            "last_name": "Arzac",
            "first_name": "Alberto",
            "email": "aarzac@gmail.com",
            "orcid": "0000-0002-3361-5349",
            "org_name": "Siberian Federal University",
            "rorid": "05fw97k56",
            "aff_department": "",
            "aff_street": "",
            "aff_plz": "",
            "aff_city": "Krasnoyarsk",
            "org_country": "RU",
            "contact_person": false
        },
        {
            "author_nr": 2,
            "last_name": "Fonti",
            "first_name": "Patrick",
            "email": "patrick.fonti@wsl.ch",
            "orcid": "0000-0002-7070-3292",
            "org_name": "Swiss Federal Institute for Forest, Snow and Landscape Research",
            "rorid": "04bs5yc70",
            "aff_department": "",
            "aff_street": "",
            "aff_plz": "",
            "aff_city": "Birmensdorf",
            "org_country": "CH",
            "contact_person": true
        },
        {
            "author_nr": 3,
            "last_name": "Naegelin",
            "first_name": "Mara",
            "email": "mara.naegelin@wsl.ch",
            "orcid": "0000-0002-0490-7510",
            "org_name": "Swiss Federal Institute for Forest, Snow and Landscape Research",
            "rorid": "04bs5yc70",
            "aff_department": "",
            "aff_street": "",
            "aff_plz": "",
            "aff_city": "Birmensdorf",
            "org_country": "CH",
            "contact_person": false
        }
    ],
    "funding_data":
    [
        {
            "org_name": "Swiss Federal Institute for Forest, Snow and Landscape Research",
            "rorid": "04bs5yc70",
            "org_country": "CH",
            "grant_name": "",
            "grant_nr": "unknown"
        }
    ],
    "relresource_data":
    [
        {
            "citation": "von Arx, G., Crivellaro, A., Prendin, A. L., Čufar, K., & Carrer, M. (2016). Quantitative Wood Anatomy—Practical Guidelines. Frontiers in Plant Science, 7. https://doi.org/10.3389/fpls.2016.00781",
            "doi": "10.3389/fpls.2016.00781"
        }
    ],
    "site_data":
    [
        {
            "site_label": "POG",
            "n_trees": 2,
            "site_name": "Pogorelsky bor",
            "site_desc": "Pogorelsky bor is a site in Russia.",
            "latitude": 56.3693,
            "longitude": 92.9552,
            "country_code": "RU",
            "elevation": 164,
            "stand_composition": "mono gymnosperm",
            "stand_structure": "regular",
            "stand_main_species_code": "",
            "stand_management": "extensive"
        },
        {
            "site_label": "STO",
            "n_trees": 1,
            "site_name": "Stolby",
            "site_desc": "Stolby is a site in Russia.",
            "latitude": 55.76,
            "longitude": 92.72,
            "country_code": "RU",
            "elevation": 450,
            "topography": "",
            "soil_depth": "",
            "stand_composition": ""
        }
    ],
    "tree_data":
    [
        {
            "tree_label": "POG_PISY_02",
            "site_label": "POG",
            "n_woodpieces": 1,
            "species_code": "PISY",
            "species_name": "Pinus sylvestris L.",
            "phylogenetic_group": "gymnosperm",
            "leaf_habit": "evergreen",
            "tree_ring_structure": "non-porous",
            "tree_treatment": "none",
            "tree_dbh": 67.2,
            "tree_height": 21.9,
            "tree_age": 85,
            "tree_social_status": "dominant",
            "tree_health_status": "healthy",
            "tree_origin": "natural regeneration",
            "wood_origin": "living"
        },
        {
            "tree_label": "POG_PISY_08",
            "site_label": "POG",
            "n_woodpieces": 1,
            "species_code": "PISY",
            "species_name": "Pinus sylvestris L.",
            "phylogenetic_group": "gymnosperm",
            "leaf_habit": "evergreen",
            "tree_ring_structure": "non-porous",
            "tree_treatment": "none",
            "tree_dbh": 48.7,
            "tree_height": 24.5,
            "tree_age": 87,
            "tree_social_status": "dominant",
            "tree_health_status": "healthy",
            "tree_origin": "natural regeneration",
            "wood_origin": "living"
        },
        {
            "tree_label": "STO_PISY_20",
            "site_label": "STO",
            "n_woodpieces": 1,
            "species_code": "PISY",
            "species_name": "Pinus sylvestris L.",
            "phylogenetic_group": "gymnosperm",
            "leaf_habit": "evergreen",
            "tree_ring_structure": "non-porous",
            "tree_treatment": "none",
            "wood_origin": "living"
        }
    ],
    "woodpiece_data":
    [
        {
            "woodpiece_label": "POG_PISY_02_B",
            "tree_label": "POG_PISY_02",
            "n_slides": 4,
            "organ": "stem",
            "sampling_height": 1.3,
            "sample_type": "core 5 mm",
            "sample_embedding": "paraffin",
            "sample_archived": true
        },
        {
            "woodpiece_label": "POG_PISY_08_B",
            "tree_label": "POG_PISY_08",
            "n_slides": 6,
            "organ": "stem",
            "sampling_height": 1.3,
            "sample_type": "core 5 mm",
            "sample_embedding": "paraffin",
            "sample_archived": true
        },
        {
            "woodpiece_label": "STO_PISY_20",
            "tree_label": "STO_PISY_20",
            "n_slides": 2,
            "organ": "stem",
            "sample_type": "core 5 mm",
            "sample_embedding": "paraffin",
            "sample_archived": true
        }
    ],
    "slide_data":
    [
        {
            "slide_label": "POG_PISY_02_B_1",
            "woodpiece_label": "POG_PISY_02_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_02_B_2",
            "woodpiece_label": "POG_PISY_02_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_02_B_3",
            "woodpiece_label": "POG_PISY_02_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_02_B_4",
            "woodpiece_label": "POG_PISY_02_B",
            "n_images": 2,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_08_B_1",
            "woodpiece_label": "POG_PISY_08_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_08_B_2",
            "woodpiece_label": "POG_PISY_08_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_08_B_3",
            "woodpiece_label": "POG_PISY_08_B",
            "n_images": 3,
            "sect_thickness": 12,
            "cutting_plane": "cross-section",
            "slide_prep": "micro-section",
            "slide_staining": "Sarafin Astrablue",
            "slide_mounting": "Euparal",
            "slide_archived": true,
            "img_cap_system": "slide scanner",
            "data_structure": "tracheid-full"
        },
        {
            "slide_label": "POG_PISY_08_B_4",
